"""Core package for HireMeTech MCP server."""

from job_mcp.core.api_client import (
    JobCache,
    calculate_match_score,
    detect_seniority_level,
    extract_candidate_profile,
    extract_cv_keywords,
    extract_dynamic_cv_skills,
    fetch_jobs_via_api,
    fetch_saved_jobs_batch,
    fetch_user_resume_profile,
    filter_jobs,
    generate_description_summary,
    parse_api_job_dict,
    resolve_cv_path,
)
from job_mcp.models.schemas import CandidateProfile
from job_mcp.core.auth import (
    BASE_URL,
    DASHBOARD_PATH,
    DEFAULT_PROFILE_DIR,
    LOGIN_PATH,
    SessionManager,
)
from job_mcp.core.browser import (
    SELECTORS,
    _resolve_selector,
    bookmark_job,
    delete_job,
    dynamic_registry,
    execute_application,
    extract_jobs,
    preview_application,
)
from job_mcp.core.discovery import (
    DynamicSelectorRegistry,
    calibrate_all_selectors,
    discover_card_selector,
    discover_child_selector,
)

__all__ = [
    "BASE_URL",
    "DASHBOARD_PATH",
    "LOGIN_PATH",
    "DEFAULT_PROFILE_DIR",
    "SessionManager",
    "SELECTORS",
    "dynamic_registry",
    "DynamicSelectorRegistry",
    "discover_card_selector",
    "discover_child_selector",
    "calibrate_all_selectors",
    "_resolve_selector",
    "extract_jobs",
    "bookmark_job",
    "delete_job",
    "preview_application",
    "execute_application",
    "JobCache",
    "CandidateProfile",
    "resolve_cv_path",
    "extract_candidate_profile",
    "extract_cv_keywords",
    "extract_dynamic_cv_skills",
    "detect_seniority_level",
    "generate_description_summary",
    "calculate_match_score",
    "filter_jobs",
    "parse_api_job_dict",
    "fetch_jobs_via_api",
    "fetch_saved_jobs_batch",
    "fetch_user_resume_profile",
]
