"""System 2 Application Tailoring & Interview Preparation Module.

Generates structured, job-specific application materials (tailored CV highlights,
custom cover letters, recruiter pitches, and interview prep questions)
using ResilientLLMGateway with guaranteed Pydantic structured output.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from job_mcp.core.llm.gateway import ResilientLLMGateway
from job_mcp.models.schemas import CandidateProfile, Job

logger = logging.getLogger(__name__)


class InterviewQuestionPrep(BaseModel):
    """Anticipated technical interview question and recommended candidate response strategy."""

    question: str = Field(description="The anticipated interview question.")
    topic: str = Field(description="The technical or behavioral topic (e.g., Python, React, Architecture, Problem Solving).")
    recommended_strategy: str = Field(description="Recommended framing and specific projects from candidate experience to highlight.")


class ApplicationPackage(BaseModel):
    """Complete tailored application package generated by System 2."""

    job_id: str = Field(description="Unique job identifier.")
    job_title: str = Field(description="Job title.")
    company: str = Field(description="Company name.")
    tailored_cv_highlights: List[str] = Field(
        description="3-5 bullet points tailoring candidate experience to this specific position.",
        min_length=2,
    )
    custom_cover_letter: str = Field(
        description="Professional, compelling cover letter customized for this company and tech stack."
    )
    recruiter_pitch: str = Field(
        description="Concise 2-3 sentence elevator pitch suitable for LinkedIn message or email intro."
    )
    interview_prep_questions: List[InterviewQuestionPrep] = Field(
        description="3-5 expected technical or situational interview questions with answering strategies.",
        min_length=2,
    )


async def generate_application_package(
    job: Job,
    profile: CandidateProfile,
    gateway: Optional[ResilientLLMGateway] = None,
) -> ApplicationPackage:
    """Generate a customized application package for a target job.

    Args:
        job: The target Job instance.
        profile: Candidate profile extracted from CV.
        gateway: Optional ResilientLLMGateway instance.

    Returns:
        ApplicationPackage: Validated structured application package.
    """
    if gateway is None:
        gateway = ResilientLLMGateway()

    candidate_skills_str = ", ".join(profile.top_skills or profile.skills or [])
    job_stack_str = ", ".join(job.tech_stack) if job.tech_stack else "General Tech Stack"

    prompt = (
        f"You are an expert technical career advisor and System 2 cognitive agent for tech hiring.\n"
        f"Generate a customized application package for candidate {profile.full_name or 'the candidate'} "
        f"applying for the position of '{job.title}' at '{job.company or 'the company'}'.\n\n"
        f"Candidate Profile:\n"
        f"- Full Name: {profile.full_name or 'Candidate'}\n"
        f"- Seniority Level: {profile.seniority_level or 'Junior/Mid'}\n"
        f"- Top Skills: {candidate_skills_str}\n"
        f"- Primary Roles: {', '.join(profile.target_roles or [])}\n\n"
        f"Target Job Details:\n"
        f"- Title: {job.title}\n"
        f"- Company: {job.company}\n"
        f"- Location: {job.location}\n"
        f"- Work Mode: {job.work_mode}\n"
        f"- Required Tech Stack: {job_stack_str}\n"
        f"- Job Description:\n{job.description[:1500]}\n\n"
        f"Requirements:\n"
        f"1. Focus heavily on overlap between candidate skills and job requirements.\n"
        f"2. Ensure tone is confident, professional, and authentic.\n"
        f"3. Provide actionable interview prep questions tailored specifically to this job's tech stack.\n"
    )

    system_prompt = (
        "You generate strict JSON adhering to the ApplicationPackage schema. "
        "Do not invent credentials; emphasize the candidate's verified skills."
    )

    try:
        raw_res = await gateway.ask_question(
            question=prompt,
            cv_context=f"Name: {profile.full_name}. Skills: {candidate_skills_str}",
            system_prompt=system_prompt,
            response_schema=ApplicationPackage,
        )

        # Parse JSON output
        parsed_data = json.loads(raw_res)
        return ApplicationPackage(**parsed_data)
    except Exception as err:
        logger.warning(
            "System 2 LLM generation failed or returned unparseable output (%s). Falling back to deterministic synthesis.",
            err,
        )
        return _synthesize_fallback_package(job, profile)


def _synthesize_fallback_package(job: Job, profile: CandidateProfile) -> ApplicationPackage:
    """Generate high-quality fallback package when offline or LLM provider unavailable."""
    name = profile.full_name or "Candidate"
    company = job.company or "the team"
    top_matches = [s for s in (profile.top_skills or []) if s in (job.tech_stack or [])]
    if not top_matches:
        top_matches = (profile.top_skills or [])[:3]

    matched_str = ", ".join(top_matches) if top_matches else "modern software engineering"

    highlights = [
        f"Hands-on expertise with {matched_str}, directly aligning with {job.title} core requirements at {company}.",
        f"Strong foundation in building scalable full-stack applications and autonomous agent pipelines.",
        f"Proven ability to rapidly master emerging technologies, maintain clean architecture, and write tested code.",
    ]

    cover_letter = (
        f"Dear Hiring Team at {company},\n\n"
        f"I am writing to express my enthusiastic interest in the {job.title} position. "
        f"With strong experience building robust solutions utilizing {matched_str}, "
        f"I am eager to contribute to {company}'s ongoing success.\n\n"
        f"My background combines hands-on engineering, clean code principles, and rapid problem-solving. "
        f"I look forward to discussing how my skills in {matched_str} will add immediate value to your team.\n\n"
        f"Sincerely,\n{name}"
    )

    recruiter_pitch = (
        f"Hi, I'm {name}, a developer specializing in {matched_str}. "
        f"I noticed the {job.title} role at {company} and would love to connect given the strong alignment with my stack!"
    )

    interview_questions = [
        InterviewQuestionPrep(
            question=f"How have you designed and deployed systems utilizing {top_matches[0] if top_matches else 'modern backend technologies'}?",
            topic="Architecture & Implementation",
            recommended_strategy="Walk through an end-to-end project, highlighting state management, API design, and testing.",
        ),
        InterviewQuestionPrep(
            question=f"Describe a challenging bug you encountered in a {job.title} environment and how you systematically resolved it.",
            topic="Systematic Debugging",
            recommended_strategy="Use the STAR method: explain the symptom, root cause hypothesis, diagnostic tools used, and verification.",
        ),
        InterviewQuestionPrep(
            question=f"How do you stay current with new AI agent frameworks, libraries, and best practices?",
            topic="Continuous Learning & Innovation",
            recommended_strategy="Mention hands-on experimentation, benchmark evaluations, and continuous project building.",
        ),
    ]

    return ApplicationPackage(
        job_id=job.job_id,
        job_title=job.title,
        company=company,
        tailored_cv_highlights=highlights,
        custom_cover_letter=cover_letter,
        recruiter_pitch=recruiter_pitch,
        interview_prep_questions=interview_questions,
    )
